function VCV_ListenerGUI
fig1=figure(1); 
color1=[1 1 0.7];
set(fig1,'MenuBar','None','NumberTitle','off',...
    'Name','Response window',...
    'Units','Normalized',...
    'Color',color1,'Resize','off')
drawnow

pos1=get(fig1,'Position');
pos1(2:4)=[0.45 0.5 0.48];
set(fig1,'Position',pos1)

% waitbar
handles1.wb1=waitbar(0,'  ','Visible','off');
c1 = get(handles1.wb1,'Children'); 
set(c1,'Parent',fig1);  % Set the position of the WAITBAR on your figure
set(c1,'Units','Normalized','Position',[0 0.02 0 0.04]);  
set(c1,'Color', [1,0.09,0.09]);
c1.Visible = 'On';
handles1.wb1 = c1;
handles1.wb1.Visible = 'On';
%


handles1.listener_text=uicontrol(fig1,'Style','Text',...
    'Units','Normalized','Position',[0.0 0.9 0.6 0.1],...
    'String','','FontSize',20,'BackgroundColor',color1);

% /b/
handles1.pb1=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',1,...
    'Units','Normalized','Position',[0.15 0.7 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','B','FontSize',25,...
    'Enable','off');

% /d/
handles1.pb2=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',2,...
    'Units','Normalized','Position',[0.35 0.7 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','D','FontSize',25,...
    'Enable','off');


% /f/ - weak
handles1.pb3=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',3,...
    'Units','Normalized','Position',[1.55 0.7 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','F','FontSize',25,...
    'Enable','inactive');

% /g/
handles1.pb4=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',4,...
    'Units','Normalized','Position',[0.55 0.7 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','G','FontSize',25,...
    'Enable','off');

% /k/
handles1.pb5=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',5,...
    'Units','Normalized','Position',[0.75 0.7 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','K','FontSize',25,...
    'Enable','off');

% /m/ - weak
handles1.pb6=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',6,...
    'Units','Normalized','Position',[1.25 0.5 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','M','FontSize',25,...
    'Enable','off');

% /n/
handles1.pb7=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',7,...
    'Units','Normalized','Position',[0.15 0.5 0.1 0.16],...
    'CallBack','enter_fun()',...
    'String','N','FontSize',25,...
    'Enable','off');

% /p/ - weak
handles1.pb8=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',8,...
    'Units','Normalized','Position',[1.65 0.5 0.1 0.1],...
    'CallBack','enter_fun()',...
    'String','P','FontSize',25,...
    'Enable','off');

% /s/
handles1.pb9=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',9,...
    'Units','Normalized','Position',[0.35 0.5 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','S','FontSize',25,...
    'Enable','off');

% /sh/
handles1.pb10=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',10,...
    'Units','Normalized','Position',[0.55 0.5 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','SH','FontSize',25,...
    'Enable','off');

% /t/
handles1.pb11=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',11,...
    'Units','Normalized','Position',[0.75 0.5 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','T','FontSize',25,...
    'Enable','off');

% /v/
handles1.pb12=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',12,...
    'Units','Normalized','Position',[0.15 0.3 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','V','FontSize',25,...
    'Enable','off');

% /z/
handles1.pb13=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',13,...
    'Units','Normalized','Position',[0.35 0.3 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','Z','FontSize',25,...
    'Enable','off');

% /Other/
handles1.pb14=uicontrol(fig1,'Style','PushButton','Tag','response','Userdata',14,...
    'Units','Normalized','Position',[0.75 0.3 0.1 0.15],...
    'CallBack','enter_fun()',...
    'String','???','FontSize',20,...
    'Enable','off');

h = findobj(gcf,'Tag','response');
set(h,'Value',0)

% axis off
% hold on

drawnow

guidata(fig1,handles1)

return
